FROM docker.io/openresty/openresty:alpine-fat
 
RUN mkdir /var/log/nginx

RUN rm -rf /etc/nginx/conf.d/*.conf
 
RUN apk add --no-cache openssl-dev
RUN apk add --no-cache git
RUN apk add --no-cache gcc
RUN luarocks install lua-resty-openidc
 
ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
EXPOSE 80
