- name: Deploy Keycloak + App
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Ensure iptables-persistent is installed
      apt:
        name: iptables-persistent
        state: present
      when: ansible_os_family == "Debian"

    - name: Add iptables rule to redirect port 80 to 8000
      iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 80
        jump: REDIRECT
        to_ports: 8000

    - name: Add iptables rule to redirect port 443 to 8443
      iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 443
        jump: REDIRECT
        to_ports: 8443

    - name: Save iptables rules
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4
