- name: Deploy Keycloak + App
  hosts: all
  become: true
  pre_tasks:
    - name: Add hosts to /etc/hosts (localhost)
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - "{{ ansible_host }} app.dpavle.local"
        - "{{ ansible_host }} keycloak.dpavle.local"

    - name: Add hosts to /etc/hosts (remote)
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - "127.0.0.1 app.dpavle.local"
        - "127.0.0.1 keycloak.dpavle.local"

    - name: Ensure iptables-persistent is installed
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Add iptables rule to redirect port 80 to 8000
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 80
        jump: REDIRECT
        to_ports: 8000

    - name: Add iptables rule to redirect port 443 to 8443
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 443
        jump: REDIRECT
        to_ports: 8443

    - name: Save iptables rules
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

- ansible.builtin.import_playbook: keycloak.yml
- ansible.builtin.import_playbook: app.yml


